/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SofieLazyImport = createFileRoute('/sofie')()
const ResevereLazyImport = createFileRoute('/resevere')()
const PhilipLazyImport = createFileRoute('/philip')()
const LoginLazyImport = createFileRoute('/login')()
<<<<<<< HEAD
const CalendarLazyImport = createFileRoute('/calendar')()
=======
const BookcardtestLazyImport = createFileRoute('/bookcardtest')()
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SofieLazyRoute = SofieLazyImport.update({
  id: '/sofie',
  path: '/sofie',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sofie.lazy').then((d) => d.Route))

const ResevereLazyRoute = ResevereLazyImport.update({
  id: '/resevere',
  path: '/resevere',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/resevere.lazy').then((d) => d.Route))

const PhilipLazyRoute = PhilipLazyImport.update({
  id: '/philip',
  path: '/philip',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/philip.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

<<<<<<< HEAD
const CalendarLazyRoute = CalendarLazyImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/calendar.lazy').then((d) => d.Route))
=======
const BookcardtestLazyRoute = BookcardtestLazyImport.update({
  id: '/bookcardtest',
  path: '/bookcardtest',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/bookcardtest.lazy').then((d) => d.Route))
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
<<<<<<< HEAD
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarLazyImport
=======
    '/bookcardtest': {
      id: '/bookcardtest'
      path: '/bookcardtest'
      fullPath: '/bookcardtest'
      preLoaderRoute: typeof BookcardtestLazyImport
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/philip': {
      id: '/philip'
      path: '/philip'
      fullPath: '/philip'
      preLoaderRoute: typeof PhilipLazyImport
      parentRoute: typeof rootRoute
    }
    '/resevere': {
      id: '/resevere'
      path: '/resevere'
      fullPath: '/resevere'
      preLoaderRoute: typeof ResevereLazyImport
      parentRoute: typeof rootRoute
    }
    '/sofie': {
      id: '/sofie'
      path: '/sofie'
      fullPath: '/sofie'
      preLoaderRoute: typeof SofieLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
<<<<<<< HEAD
  '/calendar': typeof CalendarLazyRoute
=======
  '/bookcardtest': typeof BookcardtestLazyRoute
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
  '/login': typeof LoginLazyRoute
  '/philip': typeof PhilipLazyRoute
  '/resevere': typeof ResevereLazyRoute
  '/sofie': typeof SofieLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
<<<<<<< HEAD
  '/calendar': typeof CalendarLazyRoute
=======
  '/bookcardtest': typeof BookcardtestLazyRoute
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
  '/login': typeof LoginLazyRoute
  '/philip': typeof PhilipLazyRoute
  '/resevere': typeof ResevereLazyRoute
  '/sofie': typeof SofieLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
<<<<<<< HEAD
  '/calendar': typeof CalendarLazyRoute
=======
  '/bookcardtest': typeof BookcardtestLazyRoute
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
  '/login': typeof LoginLazyRoute
  '/philip': typeof PhilipLazyRoute
  '/resevere': typeof ResevereLazyRoute
  '/sofie': typeof SofieLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
<<<<<<< HEAD
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/login'
    | '/philip'
    | '/resevere'
    | '/sofie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/login'
    | '/philip'
    | '/resevere'
    | '/sofie'
=======
  fullPaths: '/' | '/about' | '/bookcardtest' | '/login' | '/philip' | '/sofie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/bookcardtest' | '/login' | '/philip' | '/sofie'
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
  id:
    | '__root__'
    | '/'
    | '/about'
<<<<<<< HEAD
    | '/calendar'
    | '/login'
    | '/philip'
    | '/resevere'
=======
    | '/bookcardtest'
    | '/login'
    | '/philip'
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
    | '/sofie'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
<<<<<<< HEAD
  CalendarLazyRoute: typeof CalendarLazyRoute
=======
  BookcardtestLazyRoute: typeof BookcardtestLazyRoute
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
  LoginLazyRoute: typeof LoginLazyRoute
  PhilipLazyRoute: typeof PhilipLazyRoute
  ResevereLazyRoute: typeof ResevereLazyRoute
  SofieLazyRoute: typeof SofieLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
<<<<<<< HEAD
  CalendarLazyRoute: CalendarLazyRoute,
=======
  BookcardtestLazyRoute: BookcardtestLazyRoute,
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
  LoginLazyRoute: LoginLazyRoute,
  PhilipLazyRoute: PhilipLazyRoute,
  ResevereLazyRoute: ResevereLazyRoute,
  SofieLazyRoute: SofieLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
<<<<<<< HEAD
        "/calendar",
=======
        "/bookcardtest",
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
        "/login",
        "/philip",
        "/resevere",
        "/sofie"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/about": {
      "filePath": "about.lazy.jsx"
    },
<<<<<<< HEAD
    "/calendar": {
      "filePath": "calendar.lazy.jsx"
=======
    "/bookcardtest": {
      "filePath": "bookcardtest.lazy.jsx"
>>>>>>> dcc9e6022d41ce3deaed090cc92977383c37d51b
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/philip": {
      "filePath": "philip.lazy.jsx"
    },
    "/resevere": {
      "filePath": "resevere.lazy.jsx"
    },
    "/sofie": {
      "filePath": "sofie.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
