/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SofieLazyImport = createFileRoute('/sofie')()
const PhilipLazyImport = createFileRoute('/philip')()
const LoginLazyImport = createFileRoute('/login')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SofieLazyRoute = SofieLazyImport.update({
  id: '/sofie',
  path: '/sofie',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sofie.lazy').then((d) => d.Route))

const PhilipLazyRoute = PhilipLazyImport.update({
  id: '/philip',
  path: '/philip',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/philip.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/philip': {
      id: '/philip'
      path: '/philip'
      fullPath: '/philip'
      preLoaderRoute: typeof PhilipLazyImport
      parentRoute: typeof rootRoute
    }
    '/sofie': {
      id: '/sofie'
      path: '/sofie'
      fullPath: '/sofie'
      preLoaderRoute: typeof SofieLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/philip': typeof PhilipLazyRoute
  '/sofie': typeof SofieLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/philip': typeof PhilipLazyRoute
  '/sofie': typeof SofieLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/login': typeof LoginLazyRoute
  '/philip': typeof PhilipLazyRoute
  '/sofie': typeof SofieLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/login' | '/philip' | '/sofie'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/login' | '/philip' | '/sofie'
  id: '__root__' | '/' | '/about' | '/login' | '/philip' | '/sofie'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  PhilipLazyRoute: typeof PhilipLazyRoute
  SofieLazyRoute: typeof SofieLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  PhilipLazyRoute: PhilipLazyRoute,
  SofieLazyRoute: SofieLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/philip",
        "/sofie"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/about": {
      "filePath": "about.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/philip": {
      "filePath": "philip.lazy.jsx"
    },
    "/sofie": {
      "filePath": "sofie.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
